config/routes.rb
DynMachine::Engine.routes.draw do
  resources :dyn_pages
  resources :dyn_stylesheets

  root to: "dyn_pages#index"
  get "dyn_pages/build_from_tags" => "dyn_pages#build_from_tags", as: :tags
end

app/models/dyn_machine/dyn_element.rb
module DynMachine
  class DynElement < ActiveRecord::Base
    belongs_to :dyn_section, polymorphic: true
    belongs_to :dyn_nav, polymorphic: true
    belongs_to :element_parent, class_name: "Dyn_Machine::DynElement", polymorphic: true
    has_many :dyn_elements, source: "DynMachine::DynElement", as: :parent
  end
end

app/models/dyn_machine/dyn_nav.rb
module DynMachine
  class DynNav < ActiveRecord::Base
    belongs_to :dyn_theme
    has_many :dyn_elements, as: :parent
  end
end

app/models/dyn_machine/dyn_page.rb
module DynMachine
  class DynPage < ActiveRecord::Base
    belongs_to :dyn_themes
    has_many :dyn_sections

    def dyn_elements
      dyn_sections
    end
  end
end

app/models/dyn_machine/dyn_section.rb
module DynMachine
  class DynSection < ActiveRecord::Base
    belongs_to :dyn_page
    has_many :dyn_elements, as: :parent

    # validates :dyn_stylesheet, presence: true

  end
end

app/models/dyn_machine/dyn_theme.rb
module DynMachine
  class DynTheme < ActiveRecord::Base
    has_many :dyn_pages
    has_one :dyn_nav
  end
end

app/controllers/dyn_machine/application_controller.rb
module DynMachine
  class ApplicationController < ActionController::Base
  end
end

app/controllers/dyn_machine/dyn_pages_controller.rb
require_dependency "dyn_machine/page_renderer"

module DynMachine
  class DynPagesController < ApplicationController
    include DynMachine::PageRenderer

    def index
      @render_this = []

      # Create Stylesheet
      @section_ids = [DynMachine::DynSection.last.id]
      @section_ids.each{|s| @render_this << "<link href=/dyn_machine/dyn_stylesheets/#{s}.css rel=stylesheet type=text/css />"}

      # Create View
      @section_ids.each{|s| @render_this << dyn_translate(DynMachine::DynSection.find(s))}

      render html: @render_this.join.html_safe, layout: false

      # template = Sass::Rails::SassTemplate.new

      # rendering html and css from a controller {
      # @rend = []
      # @rend << '<link href="/dyn_machine/dyn_stylesheets/1.css" rel="stylesheet" type="text/css" />'
      # @rend << content_tag("div", nil, class: "div1")
      # @rend << content_tag("div", nil, class: "div2")
      # @rend = @rend.join.html_safe
      # render html: @rend
      # }

      # render :index, layout: "dyn_machine/application" #render dynamic css/html from a view
    end

  end

end

app/controllers/dyn_machine/dyn_stylesheets_controller.rb
require_dependency "dyn_machine/application_controller"
require 'dyn_machine/stylesheet_generator.rb'

module DynMachine
  class DynStylesheetsController < ApplicationController
    caches_page :show

    def show
      @section    = DynMachine::DynSection.find(params[:id])
      @stylesheet = StylesheetGenerator.new(@section).make_stylesheet
      respond_to do |format|
        # format.html {render text: @stylesheet.to_s}
        format.css  {render :text => @stylesheet, :content_type => "text/css"}
      end
    end

  end
end

app/helpers/dyn_machine/application_helper.rb
module DynMachine
  module ApplicationHelper

  end
end

app/helpers/dyn_machine/dyn_pages_helper.rb
module DynMachine
  module DynPagesHelper
  end
end

app/helpers/dyn_machine/dyn_stylesheets_helper.rb
module DynMachine
  module DynStylesheetsHelper
  end
end

app/views/dyn_machine/dyn_pages/index.html.erb
<link href="<%= "#{dyn_stylesheet_path(1)}.css" %>" rel="stylesheet" type="text/css" />
<%= link_to "Click here for stylesheet path", dyn_stylesheet_path(1) %>

<div class="div1">

</div>

app/views/layouts/dyn_machine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DynMachine</title>
  <%= stylesheet_link_tag    "dyn_machine/application", media: "all" %>
  <%= javascript_include_tag "dyn_machine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dyn_machine/test_layout.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <title>Blueprint: On Scroll Effect Layout</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="shortcut icon" href="../favicon.ico">
    <script src="js/modernizr.custom.js"></script> -->


  <%= stylesheet_link_tag "dyn_machine/test_component", "dyn_machine/test_demo", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>